CREATE PROCEDURE [dbo].[DEPARTMENTS_UPDATE_SP]
	@P_DEPARTMENT_ID INT,
	@P_DEPARTMENT_NUMBER INT,
	@P_OWNER_ID INT = NULL,
	@P_OCCUPANT_ID INT = NULL
AS
BEGIN
	UPDATE DEPARTMENTS SET 
		DEPARTMENT_NUMBER = @P_DEPARTMENT_NUMBER,
		OWNER_ID = @P_OWNER_ID,
		OCCUPANT_ID = @P_OCCUPANT_ID
		WHERE DEPARTMENT_ID = @P_DEPARTMENT_ID;
END