CREATE PROCEDURE [dbo].[OCCUPANT_VERIFY_EXIST_SP]
	@P_OCCUPANT_ID			INT,
	@P_OCCUPANT_NAME		NVARCHAR (255)
AS
BEGIN
	IF EXISTS(SELECT 1 FROM OCCUPANTS WHERE OCCUPANT_NAME = @P_OCCUPANT_NAME AND OCCUPANT_ID <> @P_OCCUPANT_ID)
	BEGIN
		RETURN 1
	END
	ELSE
		RETURN 0
END