CREATE PROCEDURE [dbo].[OCCUPANT_VERIFY_EXIST_SP]
	@P_OCCUPANT_ID			INT,
	@P_OCCUPANT_NAME		NVARCHAR (255),
	@P_RESULT BIT OUTPUT
AS
BEGIN
	IF EXISTS(SELECT 1 FROM OCCUPANTS WHERE OCCUPANT_NAME = @P_OCCUPANT_NAME AND OCCUPANT_ID <> @P_OCCUPANT_ID)
	BEGIN
		SET @P_RESULT = 1
	END
	ELSE
		SET @P_RESULT = 0

	RETURN @P_RESULT
END