CREATE PROCEDURE [dbo].[OCCUPANTS_GET_SP]

AS
BEGIN
	SELECT OCCUPANT_ID, OCCUPANT_NAME, OCCUPANT_MAIL, MOBILE_NUMBER, PHONE_NUMBER, RESPONSIBLE_NAME, RESPONSIBLE_MOBILE, COMMENTS
	FROM OCCUPANTS_VIEW
END 
GO

