CREATE PROCEDURE [dbo].[OCCUPANTS_DELETE_SP]
	@P_OCCUPANT_ID INT
AS
BEGIN 
	DELETE FROM OCCUPANTS WHERE OCCUPANT_ID = @P_OCCUPANT_ID;

	SELECT OCCUPANT_ID, OCCUPANT_NAME, OCCUPANT_MAIL, MOBILE_NUMBER, PHONE_NUMBER, RESPONSIBLE_NAME, RESPONSIBLE_MOBILE, COMMENTS
	FROM OCCUPANTS_VIEW;
END
