CREATE PROCEDURE [dbo].[OWNER_VERIFY_EXIST_SP]
	@P_OWNER_ID			INT,
	@P_OWNER_NAME		NVARCHAR (255),
	@P_RESULT BIT OUTPUT
AS
BEGIN
	IF EXISTS(SELECT 1 FROM OWNERS WHERE OWNER_NAME = @P_OWNER_NAME AND OWNER_ID <> @P_OWNER_ID)
	BEGIN 
		SET @P_RESULT = 1
	END
	ELSE
		SET @P_RESULT = 0
	
	RETURN @P_RESULT
END