CREATE PROCEDURE [dbo].[OWNERS_CREATE_SP]
	@P_OWNER_NAME NVARCHAR (255),
	@P_OWNER_MAIL NVARCHAR (255) = NULL,
	@P_PHONE_NUMBER NVARCHAR (10) = NULL,
	@P_MOBILE_NUMBER NVARCHAR(10) = NULL
AS
BEGIN
	SET NOCOUNT ON;

	 
	INSERT INTO OWNERS (OWNER_NAME, PHONE_NUMBER, MOBILE_NUMBER, OWNER_MAIL)
	VALUES (UPPER(@P_OWNER_NAME), @P_PHONE_NUMBER, @P_MOBILE_NUMBER, UPPER(@P_OWNER_MAIL));

END
