CREATE VIEW [dbo].[DEPARTMENTS_VIEW]
AS 
	SELECT DEPARTMENT_ID, DEPARTMENT_NUMBER, OW.OWNER_ID, OW.OWNER_NAME, OC.OCCUPANT_ID, OC.OCCUPANT_NAME
	FROM DEPARTMENTS D 
		INNER JOIN OWNERS OW ON D.OWNER_ID = OW.OWNER_ID
		INNER JOIN OCCUPANTS OC ON D.OCCUPANT_ID = OC.OCCUPANT_ID

