CREATE TABLE [dbo].[BALANCES_DETAILS] (
    [BALANCE_DETAIL_ID]  INT            IDENTITY (1, 1) NOT NULL,
    [BALANCE_ID]         INT            NULL,
    [PAYMENT]           MONEY          NULL,
    [PAYMENT_DATE]      DATETIME       NULL, 
    CONSTRAINT [PK_BALANCES_DETAILS] PRIMARY KEY ([BALANCE_DETAIL_ID]), 
    CONSTRAINT [FK_BALANCES_DETAILS_BALANCES] FOREIGN KEY ([BALANCE_ID]) REFERENCES [BALANCES]([BALANCE_ID]) 
);

