CREATE TABLE [dbo].[BALANCES] (
    [BALANCE_ID]             INT IDENTITY (1, 1) NOT NULL,
    [DEPARTMENT_ID]         INT NOT NULL,
    [PERIOD_DATE]           DATE NULL,
    [BALANCE_AMOUNT]        MONEY NULL, 
    CONSTRAINT [PK_BALANCES] PRIMARY KEY ([BALANCE_ID]), 
    CONSTRAINT [FK_BALANCES_DEPARTMENT] FOREIGN KEY ([DEPARTMENT_ID]) REFERENCES [DEPARTMENTS]([DEPARTMENT_ID]) 
);
