CREATE TABLE [dbo].[DEPARTMENTS] (
	[DEPARTMENT_ID]         INT NOT NULL,
	[OCCUPANT_ID]           INT NULL, 
	[OWNER_ID]              INT NULL, 
	[DEPARTMENT_NUMBER]     VARCHAR (3) NULL
	CONSTRAINT [PK_DEPARTMENT] PRIMARY KEY CLUSTERED ([DEPARTMENT_ID] ASC), 
	CONSTRAINT [FK_DEPARTMENT_OCCUPANT] FOREIGN KEY (OCCUPANT_ID) REFERENCES [OCCUPANTS]([OCCUPANT_ID]),
	CONSTRAINT [FK_DEPARTMENT_OWNER] FOREIGN KEY (OWNER_ID) REFERENCES [OWNERS]([OWNER_ID])
);

