CREATE TABLE [dbo].[OWNERS] (
    [OWNER_ID]          INT            NOT NULL IDENTITY,
    [OWNER_NAME]        NVARCHAR (255) NULL,
    [PHONE_NUMBER]      NVARCHAR (10) NULL,
    [MOBILE_NUMBER]     NVARCHAR(10) NULL, 
    CONSTRAINT [PK_OWNER] PRIMARY KEY ([OWNER_ID])
);

